-- Supabase setup para o site do casamento.
-- Cole este arquivo no SQL Editor do Supabase e execute.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  site_id text primary key default 'main',
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  full_name text not null,
  attendance text not null check (attendance in ('Sim', 'Não', 'NÃ£o')),
  adults int not null default 0 check (adults between 0 and 20),
  children int not null default 0 check (children between 0 and 20),
  email text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.guest_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.site_settings (site_id, config)
values ('main', '{}'::jsonb)
on conflict (site_id) do nothing;

alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.rsvps enable row level security;
alter table public.guest_messages enable row level security;

drop policy if exists "Admins can read admins" on public.admin_users;
create policy "Admins can read admins"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings
for select
to anon, authenticated
using (site_id = 'main');

drop policy if exists "Admins can insert site settings" on public.site_settings;
create policy "Admins can insert site settings"
on public.site_settings
for insert
to authenticated
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can update site settings" on public.site_settings;
create policy "Admins can update site settings"
on public.site_settings
for update
to authenticated
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Anyone can send RSVP" on public.rsvps;
create policy "Anyone can send RSVP"
on public.rsvps
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read RSVPs" on public.rsvps;
create policy "Admins can read RSVPs"
on public.rsvps
for select
to authenticated
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Anyone can send message" on public.guest_messages;
create policy "Anyone can send message"
on public.guest_messages
for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can read public messages" on public.guest_messages;
create policy "Public can read public messages"
on public.guest_messages
for select
to anon, authenticated
using (is_public = true);

drop policy if exists "Admins can moderate messages" on public.guest_messages;
create policy "Admins can moderate messages"
on public.guest_messages
for update
to authenticated
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

-- Depois de criar seu usuario admin em Authentication > Users,
-- rode este comando trocando o UUID pelo ID do usuario:
--
-- insert into public.admin_users (user_id)
-- values ('COLE-AQUI-O-ID-DO-USUARIO')
-- on conflict (user_id) do nothing;
